### ISSUE TITLE
Duplicate...

### ISSUE THREAD

**Issue by BedirT** [bauripalash/pydjax#3]
This repo has no difference with MathJax-Django - https://github.com/kaleidos/django-mathjax

**Comment by bauripalash** [comment]
The difference is, that don't work and mine works, check out the pull request they didn't merged , so i created my own 

https://github.com/kaleidos/django-mathjax/pull/13

**Comment by BedirT** [comment]
Even if so; if you want to continue to a project that has been stopped, you should credit the original owners + you should at least change the documentation (shouldn't copy word by word)

**Comment by bauripalash** [comment]
Actually this project was for one of my personal use project so i never thought people will take interest. 

I'll surely Update them as soon as possible. Thank You 🙂

**Comment by BedirT** [comment]
No problem, keep up with good work! 👍
