### ISSUE TITLE
Adding more Latex elements?

### ISSUE THREAD

**Issue by BedirT** [bauripalash/pydjax#4]
Any idea on how to develop more on the latex part?

For example, I have ```\vspace``` on my page and I want to add it to the rendering process if possible?

I looked through mathjax documentation but couldn't find anything; I was thinking maybe on ```MATHJAX_CONFIG_DATA``` part? But no idea how.

**Comment by bauripalash** [comment]
Not sure how to do that but this doc maybe useful : http://docs.mathjax.org/en/latest/tex.html

**Comment by BedirT** [comment]
Yup.

It is not possible 

> First and foremost, the TeX input processor implements only the math-mode macros of TeX and LaTeX, not the text-mode macros. MathJax expects that you will use standard HTML tags to handle formatting the text of your page; it only handles the mathematics. So, for example, MathJax does not implement \emph or \begin{enumerate}...\end{enumerate} or other text-mode macros or environments. You must use HTML to handle such formatting tasks. If you need a LaTeX-to-HTML converter, you should consider other options.

Thanks anyway, I guess I will try some other solution instead.
